### PR TITLE
Added Rust snippets;    

### PR DESCRIPTION
**Pull request by harontaiko**
…tp server

- basic concepts(may be removed, not really snippets)                                                - Create links on main readme for most languages

# Pull Request Template for Adding code to xzz

## Description

**Please include a summary of the changes and the related issue (if applicable).** 

- [x] This PR adds a new code sample for: [Feature/Function/Concept]
- [ ] Briefly describe the functionality or concept demonstrated by the code sample.
- [ ] Link to any relevant issues or discussions (e.g., "Closes #123").

## Checklist

Please ensure your PR meets the following requirements:

- [x] The code sample is clearly commented and easy to understand.
- [ ] The code sample adheres to the style guidelines of this repository.
- [ ] The code sample has been tested and is working as intended.
- [ ] A README.md file or inline comments have been added to explain the usage of the code sample.
- [ ] All dependencies required for the code sample are included in the appropriate file (e.g., requirements.txt, package.json).

## Type of Change

**Please select the type of change your PR introduces:**

- [x] New Code Sample
- [ ] Enhancement to Existing Code Sample
- [ ] Bug Fix in Existing Code Sample
- [ ] Documentation Update

## Testing

**Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Include any relevant details.**

- [x] Test A: [Description]
- [ ] Test B: [Description]

## Screenshots (if applicable)

**Add screenshots or screen recordings to help explain your changes.**

## Related Issues

**Please link any related issues here.**

- [Issue #123](https://github.com/your-repo/your-project/issues/123)

## Additional Notes

**Add any other context about the pull request here.**

---

## Suggested Commit Message

Use the following template for your commit message:

```
feat: Add [Feature/Function/Concept] Code Sample

- Add a new code sample demonstrating [Feature/Function/Concept].
- Ensure the code is well-commented and follows the repository's style guidelines.
- Include a README.md file or inline comments to explain the usage.
- Verify that the code sample is tested and functioning as intended.
- Update dependencies if required.

Closes #[Issue Number] if applicable.

Additional Notes:
- [Any additional notes or context about the code sample]
```

**Example:**

```
feat: Add Sorting Algorithm Code Sample

- Add a new code sample demonstrating a quicksort algorithm.
- Ensure the code is well-commented and follows the repository's style guidelines.
- Include a README.md file to explain the usage and provide examples.
- Verify that the code sample is tested and functioning as intended.
- Update dependencies if required.

Additional Notes:
- This code sample includes both iterative and recursive implementations of quicksort.
```

### CODE REVIEW

**Review by Domains18 — COMMENTED** [review]
Hello, much appreciation for your work. I would however like to request to create a sub directory inside the Rust folder titling your code.

**Review by Domains18 — CHANGES_REQUESTED** [review]
Hello, much appreciation for your work. I would however like to request to create a sub directory inside the Rust folder as your title code

**Comment by harontaiko** [comment]
You can proceed.

**Comment by nutcas3** [comment]
hello you are commiting file that you should not

**Comment by Domains18** [comment]
> hello you are commiting file that you should not

Seems I will just close the PR

**Comment by harontaiko** [comment]
will work on it an re-submit a pr

**Pull request closed without merging**
